Repository SSAFY9thBusan4-Algo/Algo-Study, pull requests merged in 2023-02, with the labels that each got.

#3 YEONGEUN CHOI : BOJ 3085 S3 사탕게임
  yeoneun/.classpath
  yeoneun/.gitignore
  yeoneun/.project
  yeoneun/src/week1/BOJ_3085_S3_사탕게임/Main.java
  yeoneun/src/week1/BOJ_3085_S3_사탕게임/README.md
  yeoneun/src/week1/readme.md
  yeoneun/week1/BOJ_3085_S3_사탕게임
  yeoneun/week1/readme.md
Labels: 👊브루트포스

#5 jihong : BOJ 3085 S3 사탕게임
  .gitignore
  jihong/week1/README.md
  kjh95044/.classpath
  kjh95044/.project
  kjh95044/src/week1/BOJ_3085_S3_사탕게임/Main.java
  kjh95044/src/week1/BOJ_3085_S3_사탕게임/readme.md
Labels: 👊브루트포스

#15 daeun : BOJ 1107 G5 리모컨
  daeun/src/week1/BOJ_1107_G5_리모컨/Main.java
  daeun/src/week1/BOJ_1107_G5_리모컨/README.md
  daeun/src/week1/BOJ_1476_S5_날짜계산/Main.java
  daeun/src/week1/BOJ_3085_S3_사탕게임/Main.java
Labels: 👊브루트포스

#35 김지홍 : BOJ 10972 S3 다음순열
  kjh95044/src/week1/BOJ_1476_S5_날짜계산/Main.java
  kjh95044/src/week1/BOJ_6064_S1_카잉달력/Main.java
  kjh95044/src/week2/BOJ_10972_S3_다음순열/BOJ_10972_S3_다음순열.java
  kjh95044/src/week2/BOJ_10972_S3_다음순열/readme.md
Labels: 🎲순조부

#24 최영은 : BOJ 10866 S4 덱
  yeongeun/src/week2/BOJ_10866_S4_덱/Main.java
  yeongeun/src/week2/BOJ_10866_S4_덱/README.md
Labels: 🔗자료구조

#36 김지홍 : BOJ 10866 S4 덱
  kjh95044/src/week2/BOJ_10866_S4_덱/BOJ_10866_S4_덱.java
  kjh95044/src/week2/BOJ_10866_S4_덱/readme.md
Labels: 🔗자료구조

#26 최영은 : BOJ 14501 S3 퇴사
  yeongeun/src/week2/BOJ_14501_S3_퇴사/Main.java
  yeongeun/src/week2/BOJ_14501_S3_퇴사/README.md
Labels: 🎲순조부

#28 최영은 : BOJ 11727 S3 2xn타일링
  yeongeun/src/week2/BOJ_11727_S3_2xn타일링2/Main.java
  yeongeun/src/week2/BOJ_11727_S3_2xn타일링2/README.md
Labels: 🏁DP

#29 최영은 : BOJ 7576 G5 토마토
  yeongeun/src/week2/BOJ_7576_G5_토마토/Main.java
  yeongeun/src/week2/BOJ_7576_G5_토마토/README.md
Labels: 🏃‍♂️DFS/BFS

#41 강다은 : BOJ 7576 G5 토마토
  daeun/src/week2/BOJ_10866_S4_덱/Main.java
  daeun/src/week2/BOJ_10972_S3_다음순열/Main.java
  daeun/src/week2/BOJ_14501_S3_퇴사/Main.java
  daeun/src/week2/BOJ_14501_S3_퇴사/README.md
  daeun/src/week2/BOJ_7576_G5_토마토/Main.java
  daeun/src/week2/BOJ_7576_G5_토마토/README.md
Labels: 🏃‍♂️DFS/BFS, ⬇️큐

#32 강소현 : BOJ 10972 S3 다음순열
  sohyeon/src/week2/BOJ_10866_S4_덱/Main.java
  sohyeon/src/week2/BOJ_10972_S3_다음순열/Main.java
  sohyeon/src/week2/BOJ_10972_S3_다음순열/README.md
Labels: 🎲순조부

#23 강다은 : BOJ 11727 S3 2xn 타일링 2
  daeun/src/week2/BOJ_11727_S3_2xn타일링2/Main.java
  daeun/src/week2/BOJ_11727_S3_2xn타일링2/README.md
Labels: 🏁DP

#45 정효인 : BOJ 7576 G5 토마토
  hyoin/src/week2/BOJ_10866_S4_덱/Main.java
  hyoin/src/week2/BOJ_10866_S4_덱/README.md
  hyoin/src/week2/BOJ_10972_S3_다음순열/Main.java
  hyoin/src/week2/BOJ_10972_S3_다음순열/README.md
  hyoin/src/week2/BOJ_11727_S3_2xn타일링2/Main.java
  hyoin/src/week2/BOJ_11727_S3_2xn타일링2/README.md
  hyoin/src/week2/BOJ_14501_S3_퇴사/Main.java
  hyoin/src/week2/BOJ_14501_S3_퇴사/README.md
  hyoin/src/week2/BOJ_7576_G5_토마토/Main.java
  hyoin/src/week2/BOJ_7576_G5_토마토/README.md
Labels: 🏃‍♂️DFS/BFS

#42 강소현 : BOJ 7576 G5 토마토
  .gitignore
  sohyeon/.classpath
  sohyeon/.project
  sohyeon/src/week2/BOJ_10866_S4_덱/README.md
  sohyeon/src/week2/BOJ_11727_S3_2xn타일링2/Main.java
  sohyeon/src/week2/BOJ_11727_S3_2xn타일링2/README.md
  sohyeon/src/week2/BOJ_14501_S3_퇴사/README.md
  sohyeon/src/week2/BOJ_7576_G5_토마토/Main.java
  sohyeon/src/week2/BOJ_7576_G5_토마토/README.md
Labels: 🔄 재귀, 🏃‍♂️DFS/BFS, ⬇️큐

#71 김지홍 : PRG 60058 LV2 괄호변환
  kjh95044/src/week3/PRG_60058_LV2_괄호변환/PRG_60058_LV2_괄호변환.java
  kjh95044/src/week3/PRG_60058_LV2_괄호변환/readme.md
Labels: 🤜구현

#55 최영은 : BOJ 1991 S1 트리순회
  yeongeun/src/week3/BOJ_1991_S1_트리순회/Main.java
  yeongeun/src/week3/BOJ_1991_S1_트리순회/README.md
Labels: 🔄 재귀

#57 최영은 : BOJ 1992 S1 쿼드트리
  yeongeun/src/week3/BOJ_1992_S1_쿼드트리/Main.java
  yeongeun/src/week3/BOJ_1992_S1_쿼드트리/README.md
Labels: 🔄 재귀

#66 최영은 : PRG 60058 LV2 괄호변환
  yeongeun/src/week3/PRG_60058_LV2_괄호변환/README.md
  yeongeun/src/week3/PRG_60058_LV2_괄호변환/Solution.java
Labels: 🤜구현

#69 김지홍 : BOJ 1991 S1 트리순회
  kjh95044/src/week3/BOJ_1991_S1_트리순회/BOJ_1991_S1_트리순회.java
  kjh95044/src/week3/BOJ_1991_S1_트리순회/readme.md
Labels: 🔄 재귀

#68 김지홍 : BOJ 9084 G5 동전
  kjh95044/src/week3/BOJ_9084_G5_동전/BOJ_9084_G5_동전.java
  kjh95044/src/week3/BOJ_9084_G5_동전/readme.md
Labels: 🏁DP

#64 정효인 : BOJ 9084 G5 동전
  hyoin/src/week3/BOJ_9084_G5_동전/Main.java
  hyoin/src/week3/BOJ_9084_G5_동전/README.md
  hyoin/src/week3/README.md
Labels: 🏁DP

#65 강다은 : PRG 60058 LV2 괄호 변환
  daeun/src/week3/PRG_60058_LV2_괄호변환/Main.java
  daeun/src/week3/PRG_60058_LV2_괄호변환/README.md
Labels: 🤜구현

#54 강다은 : BOJ 1991 S1 트리 순회
  daeun/src/week3/BOJ_1991_S1_트리순회/Main.java
  daeun/src/week3/BOJ_1991_S1_트리순회/README.md
Labels: 🔄 재귀

#59 강다은 : BOJ 9084 G5 동전
  daeun/src/week3/BOJ_9084_G5_동전/Main.java
  daeun/src/week3/BOJ_9084_G5_동전/README.md
Labels: 🏁DP

#52 강소현 : BOJ 1991 S1 트리순회
  sohyeon/src/week3/BOJ_1991_S1_트리순회/Main.java
  sohyeon/src/week3/BOJ_1991_S1_트리순회/README.md
Labels: 🔄 재귀

#53 강소현 : BOJ 1992 S2 쿼드트리
  sohyeon/src/week3/BOJ_1992_S1_쿼드트리/Main.java
  sohyeon/src/week3/BOJ_1992_S1_쿼드트리/README.md
Labels: 🔄 재귀

#58 강소현 : PRG 60058 LV2 괄호변환
  sohyeon/src/week3/PRG_60058_LV2_괄호변환/Main.java
  sohyeon/src/week3/PRG_60058_LV2_괄호변환/README.md
Labels: 🤜구현

#60 강소현 : BOJ 9084 G5 동전
  sohyeon/src/week3/BOJ_9084_G5_동전/Main.java
  sohyeon/src/week3/BOJ_9084_G5_동전/README.md
Labels: 🏁DP
