Repository SSAFY9thBusan4-Algo/Algo-Study, pull requests merged in 2023-05, with the labels that each got.

#323 김지홍 : BOJ 9935 G4 문자열 폭발
  kjh95044/src/week13/BOJ_9935_G4_문자열폭발/BOJ_9935_G4_문자열폭발.java
  kjh95044/src/week13/BOJ_9935_G4_문자열폭발/readme.md
Labels: 🤜구현

#325 김지홍 : BOJ 13164 G5 행복유치원
  kjh95044/src/week13/BOJ_13164_G5_행복유치원/BOJ_13164_G5_행복유치원.java
  kjh95044/src/week13/BOJ_13164_G5_행복유치원/readme.md
Labels: 💰 그리디

#319 최영은 : BOJ 22251 G5 빌런호석
  yeongeun/src/week13/BOJ_22251_G5_빌런호석/Main.java
  yeongeun/src/week13/BOJ_22251_G5_빌런호석/README.md
Labels: 👊브루트포스, 🤜구현

#320 최영은 : BOJ 9935 G4 문자열폭발
  yeongeun/src/week13/BOJ_9935_G4_문자열폭발/Main.java
  yeongeun/src/week13/BOJ_9935_G4_문자열폭발/README.md
Labels: 🪟슬라이딩 윈도우, 💬 문자열

#321 최영은 : BOJ 2879 G3 코딩은예쁘게
  yeongeun/src/week13/BOJ_2879_G3_코딩은예쁘게/Main.java
  yeongeun/src/week13/BOJ_2879_G3_코딩은예쁘게/README.md
Labels: 💰 그리디

#322 최영은 : BOJ 13164 G5 행복유치원
  yeongeun/src/week13/BOJ_13164_G5_행복유치원/Main.java
  yeongeun/src/week13/BOJ_13164_G5_행복유치원/README.md
Labels: 💰 그리디

#324 강소현 : BOJ 2879 G3 코딩은예쁘게
  sohyeon/src/week13/BOJ_2879_G3_코딩은예쁘게/Main.java
  sohyeon/src/week13/BOJ_2879_G3_코딩은예쁘게/README.md
Labels: 💰 그리디

#327 강소현 : BOJ 9935 G4 문자열폭발
  sohyeon/src/week13/BOJ_9935_G4_문자열폭발/Main.java
  sohyeon/src/week13/BOJ_9935_G4_문자열폭발/README.md
Labels: 💬 문자열

#328 강소현 : BOJ 22251 G5 빌런호석
  sohyeon/src/week13/BOJ_22251_G5_빌런호석/Main.java
  sohyeon/src/week13/BOJ_22251_G5_빌런호석/README.md
Labels: 🤜구현

#308 강다은 : BOJ 9935 G4 문자열 폭발
  daeun/src/week13/BOJ_9935_G4_문자열폭발/Main.java
  daeun/src/week13/BOJ_9935_G4_문자열폭발/Read.md
Labels: 🔗자료구조

#309 강다은 : BOJ 13164 G5 행복유치원
  daeun/src/week13/BOJ_13164_G5_행복유치원/Main.java
  daeun/src/week13/BOJ_13164_G5_행복유치원/README.md
Labels: 🔗자료구조, 💰 그리디

#310 강다은 : BOJ 22251 G5 빌런 호석
  daeun/src/week13/BOJ_22251_G5_빌런호석/Main.java
  daeun/src/week13/BOJ_22251_G5_빌런호석/README.md
Labels: 🤜구현

#318 강다은 : BOJ 2879 G3 코딩은 예쁘게
  daeun/src/week13/BOJ_2879_G3_코딩은예쁘게/Main.java
  daeun/src/week13/BOJ_2879_G3_코딩은예쁘게/README.md
Labels: 💰 그리디

#329 이동주 : BOJ 9935 G4 문자열폭발
  dongju/src/week13/BOJ-9935-G4-문자열폭발/BOJ-9935-G4-문자열폭발.java
  dongju/src/week13/BOJ-9935-G4-문자열폭발/README.md
Labels: 💬 문자열

#317 이동주 : BOJ 2879 G3 코딩은예쁘게
  dongju/src/week13/ BOJ-2879-G3-코딩은예쁘게/BOJ-2879-G3-코딩은예쁘게.java
  dongju/src/week13/ BOJ-2879-G3-코딩은예쁘게/README.md
Labels: 💰 그리디

#311 이동주 : BOJ 13164 G5 행복유치원
  dongju/src/week13/BOJ-13164-G5-행복유치원/BOJ-13164-G5-행복유치원.java
  dongju/src/week13/BOJ-13164-G5-행복유치원/README.md
Labels: 💰 그리디

#313 정효인 : BOJ 9935 G4 문자열 폭발
  hyoin/src/week13/BOJ_9935_G4_문자열폭발/BOJ_9935_G4_문자열폭발.java
  hyoin/src/week13/BOJ_9935_G4_문자열폭발/README.md
  hyoin/src/week13/README.md
Labels: 🔗자료구조

#355 김지홍 : BOJ 2866 G5 문자열 잘라내기
  kjh95044/src/week14/BOJ_2866_G5_문자열잘라내기/BOJ_2866_G5_문자열잘라내기.java
  kjh95044/src/week14/BOJ_2866_G5_문자열잘라내기/readme.md
Labels: 🔗자료구조

#353 김지홍 : BOJ 2668 G5 숫자고르기
  kjh95044/src/week14/BOJ_2668_G5_숫자고르기/BOJ_2668_G5_숫자고르기.java
  kjh95044/src/week14/BOJ_2668_G5_숫자고르기/readme.md
Labels: 🏃‍♂️DFS/BFS

#352 김지홍 : BOJ 11724 S2 연결요소의개수
  kjh95044/src/week14/BOJ_11724_S2_연결요소의개수/BOJ_11724_S2_연결요소의개수.java
  kjh95044/src/week14/BOJ_11724_S2_연결요소의개수/readme.md
Labels: 🏃‍♂️DFS/BFS

#351 김지홍 : BOJ 2529 S1 부등호
  kjh95044/src/week14/BOJ_2529_S1_부등호/BOJ_2529_S1_부등호.java
  kjh95044/src/week14/BOJ_2529_S1_부등호/readme.md
Labels: 👊브루트포스

#350 김지홍 : BOJ 16463 S3 13일의 금요일
  kjh95044/src/week14/BOJ_16463_S3_13일의금요일/BOJ_16463_S3_13일의금요일.java
  kjh95044/src/week14/BOJ_16463_S3_13일의금요일/readme.md
Labels: 🤜구현

#338 강다은 : BOJ 11724 S2 연결요소의 개수
  daeun/src/week14/BOJ_11724_S2_연결요소의개수/Main.java
  daeun/src/week14/BOJ_11724_S2_연결요소의개수/README.md
Labels: 🏃‍♂️DFS/BFS, 👨🏻‍🤝‍👨🏻그래프

#337 강다은 : BOJ 2529 S1 부등호
  daeun/src/week14/BOJ_2529_S1_부등호/Main.java
  daeun/src/week14/BOJ_2529_S1_부등호/README.md
Labels: 🎲순조부

#331 강다은 : BOJ 2866 G5 문자열 잘라내기
  daeun/src/week14/BOJ_2866_G5_문자열잘라내기/Main.java
  daeun/src/week14/BOJ_2866_G5_문자열잘라내기/Main1.java
  daeun/src/week14/BOJ_2866_G5_문자열잘라내기/README.md
Labels: 💬 문자열

#330 강다은 : BOJ 16463 S3 13일의 금요일
  daeun/src/week14/BOJ_16463_S3_13일의금요일/Main.java
  daeun/src/week14/BOJ_16463_S3_13일의금요일/README.md
Labels: 🤜구현

#346 정효인 : BOJ 2529 S1 부등호
  hyoin/src/week14/BOJ_2529_S1_부등호/BOJ_2529_S1_부등호.java
  hyoin/src/week14/BOJ_2529_S1_부등호/README.md
  hyoin/src/week14/README.md
Labels: 🎲순조부

#339 강다은 : BOJ 2668 G5 숫자 고르기
  daeun/src/week14/BOJ_2668_G5_숫자고르기/Main.java
  daeun/src/week14/BOJ_2668_G5_숫자고르기/README.md
Labels: 🔄 재귀, 🏃‍♂️DFS/BFS

#349 이동주 : BOJ 11724 S2 연결요소의개수
  dongju/src/week14/BOJ-11724-S2-연결요소의개수/BOJ-11724-S2-연결요소의개수.java
  dongju/src/week14/BOJ-11724-S2-연결요소의개수/README.md
Labels: 👨🏻‍🤝‍👨🏻그래프

#334 강소현 : BOJ 2866 G5 문자열 잘라내기
  sohyeon/src/week14/BOJ_2866_G5_문자열잘라내기/Main.java
  sohyeon/src/week14/BOJ_2866_G5_문자열잘라내기/README.md
Labels: 💬 문자열

#335 강소현 : BOJ 11724 S2 연결요소의개수
  sohyeon/src/week14/BOJ_11724_S2_연결요소의개수/Main.java
  sohyeon/src/week14/BOJ_11724_S2_연결요소의개수/README.md
Labels: 👨🏻‍🤝‍👨🏻그래프

#336 강소현 : BOJ 16463 S3 13일의금요일
  sohyeon/src/week14/BOJ_16463_S3_13일의금요일/Main.java
  sohyeon/src/week14/BOJ_16463_S3_13일의금요일/README.md
Labels: 🤜구현

#354 최영은 : BOJ 2668 G5 숫자고르기
  yeongeun/src/week14/BOJ_2668_G5_숫자고르기/Main.java
  yeongeun/src/week14/BOJ_2668_G5_숫자고르기/README.md
Labels: 🏃‍♂️DFS/BFS

#343 최영은 : BOJ 2866 G5 문자열잘라내기
  yeongeun/src/week14/BOJ_2866_G5_문자열잘라내기/Main.java
  yeongeun/src/week14/BOJ_2866_G5_문자열잘라내기/README.md
Labels: 💬 문자열

#342 최영은 : BOJ 2529 S1 부등호
  yeongeun/src/week14/BOJ_2529_S1_부등호/Main.java
  yeongeun/src/week14/BOJ_2529_S1_부등호/README.md
Labels: 🏃‍♂️DFS/BFS

#341 최영은 : BOJ 11724 S2 연결요소의개수
  yeongeun/src/week14/BOJ_11724_S2_연결요소의개수/Main.java
  yeongeun/src/week14/BOJ_11724_S2_연결요소의개수/README.md
Labels: 👨🏻‍🤝‍👨🏻그래프

#340 최영은 : BOJ 16463 S3 13일의금요일
  yeongeun/src/week14/BOJ_16463_S3_13일의금요일/Main.java
  yeongeun/src/week14/BOJ_16463_S3_13일의금요일/README.md
Labels: 🤜구현

#359 강다은 : BOJ 1461 G5 도서관
  daeun/src/week15/BOJ_1461_G5_도서관/Main.java
  daeun/src/week15/BOJ_1461_G5_도서관/README.md
Labels: 💰 그리디

#360 강다은 : BOJ 5052 G4 전화번호 목록
  daeun/src/week15/BOJ_5052_G4_전화번호목록/Main.java
  daeun/src/week15/BOJ_5052_G4_전화번호목록/README.md
Labels: 💬 문자열

#361 강다은 : BOJ_16139_S1_컴퓨터상호작용
  daeun/src/week15/BOJ_16139_S1_컴퓨터상호작용/Main.java
  daeun/src/week15/BOJ_16139_S1_컴퓨터상호작용/README.md
Labels: 🤜구현, 🫴누적합

#367 정효인 : BOJ 15685 G4 드래곤 커브
  hyoin/src/week15/BOJ_15685_G4_드래곤커브/BOJ_15685_G4_드래곤커브.java
  hyoin/src/week15/BOJ_15685_G4_드래곤커브/README.md
  hyoin/src/week15/README.md
Labels: 🤜구현

#366 이동주 : BOJ 5052 G4 전화번호목록
  dongju/src/week15/BOJ-5052-G4-전화번호목록/BOJ-5052-G4-전화번호목록.java
  dongju/src/week15/BOJ-5052-G4-전화번호목록/README.md
Labels: 🔗자료구조

#358 이동주 : BOJ 1461 G5 도서관
  dongju/src/week15/BOJ-1461-G5-도서관/BOJ-1461-G5-도서관.java
  dongju/src/week15/BOJ-1461-G5-도서관/README.md
Labels: 💰 그리디

#357 이동주 : BOJ 15685 G4 드래곤커브
  dongju/src/week15/BOJ-15685-G4-드래곤커브/BOJ-15685-G4-드래곤커브.java
  dongju/src/week15/BOJ-15685-G4-드래곤커브/README.md
Labels: 🤜구현

#356 이동주 : BOJ 16139 S1 인간컴퓨터상호작용
  dongju/src/week15/BOJ-16139-S1-인간컴퓨터상호작용/BOJ-16139-S1-인간컴퓨터상호작용.java
  dongju/src/week15/BOJ-16139-S1-인간컴퓨터상호작용/README.md
Labels: 🫴누적합

#379 김지홍 : BOJ 14620 S2 꽃길
  kjh95044/src/week15/BOJ_14620_S2_꽃길/BOJ_14620_S2_꽃길.java
  kjh95044/src/week15/BOJ_14620_S2_꽃길/readme.md
Labels: 🎲순조부

#380 김지홍 : BOJ 2166 G5 다각형의면적
  kjh95044/src/week16/BOJ_2166_G5_다각형의면적/BOJ_2166_G5_다각형의면적.java
  kjh95044/src/week16/BOJ_2166_G5_다각형의면적/readme.md
Labels: 수학

#378 강다은 : BOJ 14442 G3 벽 부수고 이동하기 2
  daeun/src/week16/BOJ_14442_G3_벽부수고이동하기2/Main.java
  daeun/src/week16/BOJ_14442_G3_벽부수고이동하기2/README.md
Labels: 🏃‍♂️DFS/BFS

#369 강다은 : BOJ 2166 G5 다각형의 면적
  daeun/src/week16/BOJ_2166_G5_다각형의면적/Main.java
  daeun/src/week16/BOJ_2166_G5_다각형의면적/README.md
Labels: 🤜구현, 수학

#370 강다은 : BOJ 14620 S2 꽃길
  daeun/src/week16/BOJ_14620_S2_꽃길/Main.java
  daeun/src/week16/BOJ_14620_S2_꽃길/README.md
Labels: 🎲순조부

#377 강다은 : BOJ 2531 S1 회전초밥
  daeun/src/week16/BOJ_2531_S1_회전초밥/Main.java
  daeun/src/week16/BOJ_2531_S1_회전초밥/README.md
Labels: 🪟슬라이딩 윈도우

#392 이동주 : BOJ 2166 G5 다각형의면적
  dongju/src/week16/BOJ-2166-G5-다각형의면적/BOJ-2166-G5-다각형의면적.java
  dongju/src/week16/BOJ-2166-G5-다각형의면적/README.md
Labels: 수학

#381 이동주 : BOJ 14442 G3 벽부수고이동하기2
  dongju/src/week16/BOJ-14442-G3-벽부수고이동하기2/BOJ-14442-G3-벽부수고이동하기2.java
  dongju/src/week16/BOJ-14442-G3-벽부수고이동하기2/README.md
Labels: 🏃‍♂️DFS/BFS

#372 이동주 : BOJ 2531 S1 회전초밥
  dongju/src/week16/BOJ-2531-S1-회전초밥/BOJ-2531-S1-회전초밥.java
  dongju/src/week16/BOJ-2531-S1-회전초밥/README.md
Labels: 🪟슬라이딩 윈도우

#371 이동주 : BOJ 14620 S2 꽃길
  dongju/src/week16/BOJ-14620-S2-꽃길/BOJ-14620-S2-꽃길.java
  dongju/src/week16/BOJ-14620-S2-꽃길/README.md
Labels: 👊브루트포스
