Repository SSAFY9thBusan4-Algo/Algo-Study, pull requests merged in 2023-10, with the labels that each got.

#623 강다은 : BOJ 19941 S3 햄버거 분배
  daeun/src/week31/BOJ_19941_S3_햄버거분배/Main.java
  daeun/src/week31/BOJ_19941_S3_햄버거분배/README.md
Labels: 💰 그리디

#624 최연재 : BOJ 20125 S4 쿠키의신체측정
  yeonjae/src/week28/BOJ_20125_쿠키의신체측정/BOJ20125.java
  yeonjae/src/week28/BOJ_20125_쿠키의신체측정/README.md
Labels: 🤜구현

#625 최연재 : BOJ 24511 S3 queuestack
  yeonjae/src/week28/BOJ_24511_queuestack/BOJ24511.java
  yeonjae/src/week28/BOJ_24511_queuestack/README.md
Labels: ⬇️큐, 📚스택

#626 최연재 : BOJ 22233 S2 가희와 키워드
  yeonjae/src/week28/BOJ_22233_가희와키워드/BOJ22233.java
  yeonjae/src/week28/BOJ_22233_가희와키워드/README.md
Labels: 🤜구현

#627 최연재 : BOJ 9657 S3 돌게임3
  yeonjae/src/week30/BOJ_9657_돌게임3/BOJ9657.java
  yeonjae/src/week30/BOJ_9657_돌게임3/README.md
Labels: 🏁DP

#628 최연재 : BOJ 16165 S3 걸그룹마스터준석이
  yeonjae/src/week30/BOJ_16165_걸그룹마스터준석이/BOJ16165.java
  yeonjae/src/week30/BOJ_16165_걸그룹마스터준석이/README.md
  yeonjae/src/week30/BOJ_16165_걸그룹마스터준식이/BOJ16165.java
Labels: 🤜구현

#629 최연재 : BOJ 2473 G3 세용액
  yeonjae/src/week28/BOJ_2473_세용액/BOJ2473.java
  yeonjae/src/week28/BOJ_2473_세용액/README.md
Labels: 🔫투포인터

#630 최연재 : BOJ 11048 S2 이동하기
  yeonjae/src/week29/BOJ_11048_이동하기/BOJ11048.java
  yeonjae/src/week29/BOJ_11048_이동하기/README.md
Labels: 🏁DP

#631 최연재 : BOJ 20922 S1 겹치는건싫어
  yeonjae/src/week29/BOJ_20922_겹치는건싫어/BOJ20922.java
  yeonjae/src/week29/BOJ_20922_겹치는건싫어/README.md
Labels: 🔫투포인터

#632 최연재 : BOJ 16948 S1 데스나이트
  yeonjae/src/week29/BOJ_16948_데스나이트/BOJ16948.java
  yeonjae/src/week29/BOJ_16948_데스나이트/README.md
Labels: 🏃‍♂️DFS/BFS

#633 최연재 : BOJ 20291 S3 파일정리
  yeonjae/src/week31/BOJ_20291_파일정리/BOJ20291.java
  yeonjae/src/week31/BOJ_20291_파일정리/README.md
Labels: ⛑Map

#634 최연재 : BOJ 19941 S3 햄버거분배
  yeonjae/src/week31/BOJ_19941_햄버거분배/BOJ19941.java
  yeonjae/src/week31/BOJ_19941_햄버거분배/README.md
Labels: 🤜구현

#635 최연재 : BOJ 1138 S2 한줄로서기
  yeonjae/src/week31/BOJ_1138_한줄로서기/BOJ1138.java
  yeonjae/src/week31/BOJ_1138_한줄로서기/README.md
Labels: 🤜구현

#636 최연재 : BOJ 2800 G5 괄호제거
  yeonjae/src/week31/BOJ_2800_괄호제거/BOJ2800.java
  yeonjae/src/week31/BOJ_2800_괄호제거/README.md
Labels: ↩ 백트레킹

#637 최연재 : BOJ 2482 G3 색상환
  yeonjae/src/week29/BOJ_2482_색상환/BOJ2482.java
  yeonjae/src/week29/BOJ_2482_색상환/README.md
Labels: 🏁DP

#638 최연재 : BOJ 1644 G3 소수의연속합
  yeonjae/src/week30/BOJ_1644_소수의연속합/BOJ1644.java
  yeonjae/src/week30/BOJ_1644_소수의연속합/README.md
Labels: 🔫투포인터

#639 최연재 : BOJ 7682 G5 틱택토
  yeonjae/src/week30/BOJ_7682_틱택토/BOJ7682.java
  yeonjae/src/week30/BOJ_7682_틱택토/README.md
Labels: 🤜구현
