Repository SSAFY9thBusan4-Algo/Algo-Study, pull requests merged in 2023-06, with the labels that each got.

#390 최영은 : BOJ 2531 S1 회전초밥
  yeongeun/src/week16/BOJ_2531_S1_회전초밥/Main2531_S1_회전초밥.java
  yeongeun/src/week16/BOJ_2531_S1_회전초밥/README.md
Labels: 🪟슬라이딩 윈도우

#386 최영은 : BOJ 14620 S2 꽃길
  yeongeun/src/week16/BOJ_14620_S2_꽃길/Main14620_S2_꽃길.java
  yeongeun/src/week16/BOJ_14620_S2_꽃길/README.md
Labels: 🎲순조부

#383 최영은 : BOJ 14442 G3 벽부수고이동하기2
  yeongeun/src/week16/BOJ_14442_G3_벽부수고이동하기2/Main14442_G3_벽부수고이동하기2.java
  yeongeun/src/week16/BOJ_14442_G3_벽부수고이동하기2/README.md
Labels: 🏃‍♂️DFS/BFS

#384 강소현 : BOJ 2166 G5 다각형의면적
  sohyeon/src/week16/BOJ_2166_G5_다각형의면적/Main.java
  sohyeon/src/week16/BOJ_2166_G5_다각형의면적/README.md
Labels: 수학

#385 강소현 : BOJ 2531 S1 회전초밥
  sohyeon/src/week16/BOJ_2531_S1_회전초밥/Main.java
  sohyeon/src/week16/BOJ_2531_S1_회전초밥/README.md
Labels: 🪟슬라이딩 윈도우

#387 강소현 : BOJ 14442 G3 벽부수고이동하기2
  sohyeon/src/week16/BOJ_14442_G3_벽부수고이동하기2/Main.java
  sohyeon/src/week16/BOJ_14442_G3_벽부수고이동하기2/README.md
Labels: 🏃‍♂️DFS/BFS

#388 강소현 : BOJ 14620 S2 꽃길
  sohyeon/src/week16/BOJ_14620_S2_꽃길/Main.java
  sohyeon/src/week16/BOJ_14620_S2_꽃길/README.md
Labels: 🤜구현

#413 이동주 : BOJ 18430 G4 무기공학
  dongju/src/week17/BOJ-18430-G4-무기공학/BOJ-18430-G4-무기공학.java
  dongju/src/week17/BOJ-18430-G4-무기공학/README.md
Labels: 👊브루트포스

#406 이동주 : BOJ 12886 G4 돌그룹
  dongju/src/week17/BOJ-12886-G4-돌그룹/BOJ-12886-G4-돌그룹.java
  dongju/src/week17/BOJ-12886-G4-돌그룹/README.md
Labels: 🏃‍♂️DFS/BFS

#405 이동주 : BOJ 1647 G4 도시분할계획
  dongju/src/week17/BOJ-1647-G4-도시분할계획/BOJ-1647-G4-도시분할계획.java
  dongju/src/week17/BOJ-1647-G4-도시분할계획/README.md
Labels: 👨🏻‍🤝‍👨🏻그래프

#393 이동주 : BOJ 2156 S1 포도주시식
  dongju/src/week17/BOJ-2156-S1-포도주시식/BOJ-2156-S1-포도주시식.java
  dongju/src/week17/BOJ-2156-S1-포도주시식/README.md
Labels: 🏁DP

#408 김지홍 : BOJ 18430 G4 무기공학
  kjh95044/src/week17/BOJ_18430_G4_무기공학/BOJ_18430_G4_무기공학.java
  kjh95044/src/week17/BOJ_18430_G4_무기공학/readme.md
Labels: 🏃‍♂️DFS/BFS

#407 김지홍 : BOJ 2156 S1 포도주시식
  kjh95044/src/week17/BOJ_2156_S1_포도주시식/BOJ_2156_S1_포도주시식.java
  kjh95044/src/week17/BOJ_2156_S1_포도주시식/readme.md
Labels: 🏁DP

#404 김지홍 : BOJ 12886 G4 돌 그룹
  kjh95044/src/week17/BOJ_12886_G4_돌그룹/BOJ_12886_G4_돌그룹.java
  kjh95044/src/week17/BOJ_12886_G4_돌그룹/readme.md
Labels: 🏃‍♂️DFS/BFS

#403 김지홍 : BOJ 1647 G4 도시분할계획
  kjh95044/src/week17/BOJ_1647_G4_도시분할계획/BOJ_1647_G4_도시분할계획.java
  kjh95044/src/week17/BOJ_1647_G4_도시분할계획/readme.md
Labels: 👨🏻‍🤝‍👨🏻그래프

#397 강다은 : BOJ 1647 G4 도시 분할 계획
  daeun/src/week17/BOJ_1647_G4_도시분할계획/Main1.java
  daeun/src/week17/BOJ_1647_G4_도시분할계획/Main2.java
  daeun/src/week17/BOJ_1647_G4_도시분할계획/README.md
Labels: 👨🏻‍🤝‍👨🏻그래프

#396 강다은 : BOJ 18430 G4 무기 공학
  daeun/src/week17/BOJ_18430_G4_무기공학/Main.java
  daeun/src/week17/BOJ_18430_G4_무기공학/README.md
Labels: 🤜구현

#395 강다은 : BOJ 2156 S1 포도주 시식
  daeun/src/week17/BOJ_2156_S1_포도주시식/Main.java
  daeun/src/week17/BOJ_2156_S1_포도주시식/README.md
Labels: 🏁DP

#394 강다은 : BOJ 12886 G4 돌 그룹
  daeun/src/week17/BOJ_12886_G4_돌그룹/Main.java
  daeun/src/week17/BOJ_12886_G4_돌그룹/README.md
Labels: 🏃‍♂️DFS/BFS

#398 최연재 : BOJ 1647 G4 도시 분할 계획
  yeonjae/src
  yeonjae/src/week17/BOJ_1647_도시분할계획/BOJ1647.java
  yeonjae/src/week17/BOJ_1647_도시분할계획/README.md
Labels: 👨🏻‍🤝‍👨🏻그래프

#409 강소현 : BOJ 1647 G4 도시분할계획
  sohyeon/src/week17/BOJ_1647_G4_도시분할계획/Main.java
  sohyeon/src/week17/BOJ_1647_G4_도시분할계획/README.md
Labels: 👨🏻‍🤝‍👨🏻그래프

#410 강소현 : BOJ 2156 S1 포도주시식
  sohyeon/src/week17/BOJ_2156_S1_포도주시식/Main.java
  sohyeon/src/week17/BOJ_2156_S1_포도주시식/README.md
Labels: 🏁DP

#445 이동주 : BOJ 2666 G5 벽장문의이동
  dongju/src/week18/BOJ-2666-G5-벽장문의이동/BOJ-2666-G5-벽장문의이동.java
  dongju/src/week18/BOJ-2666-G5-벽장문의이동/README.md
Labels: 🏃‍♂️DFS/BFS

#437 이동주 : BOJ 1937 G3 욕심쟁이판다
  dongju/src/week18/BOJ-1937-G3-욕심쟁이판다/BOJ-1937-G3-욕심쟁이판다.java
  dongju/src/week18/BOJ-1937-G3-욕심쟁이판다/README.md
Labels: 🏁DP, 🏃‍♂️DFS/BFS

#436 이동주 : BOJ 17218 G5 비밀번호 만들기
  dongju/src/week18/BOJ-17218-G5-비밀번호-만들기/BOJ-17218-G5-비밀번호-만들기.java
  dongju/src/week18/BOJ-17218-G5-비밀번호-만들기/README.md
Labels: 🏁DP, 💬 문자열

#435 이동주 : BOJ 16197 G4 두동전
  dongju/src/week18/BOJ-16197-G4-두동전/BOJ-16197-G4-두동전.java
  dongju/src/week18/BOJ-16197-G4-두동전/README.md
Labels: 🏃‍♂️DFS/BFS

#418 이하린 : BOJ 1937 G3 욕심쟁이 판다
  harin/week18/BOJ_1937_G3_욕심쟁이판다/BOJ_1937_G3_욕심쟁이판다.java
  harin/week18/BOJ_1937_G3_욕심쟁이판다/README.md
Labels: 🏁DP, 🏃‍♂️DFS/BFS

#419 이하린 : BOJ 17836 G5 공주님을 구해라!
  harin/week18/BOJ_17836_G5_공주님을구해라/BOJ_17836_G5_공주님을구해라.java
  harin/week18/BOJ_17836_G5_공주님을구해라/README.md
Labels: 🏃‍♂️DFS/BFS

#423 이하린 : BOJ 16197 G4 두 동전
  harin/week18/BOJ_16197_G4_두동전/BOJ_16197_G4_두동전.java
  harin/week18/BOJ_16197_G4_두동전/README.md
Labels: 🏃‍♂️DFS/BFS

#414 최연재 : BOJ 17836 공주님을 구해라!
  yeonjae/src/week18/BOJ_17836_공주님을구해라/BOJ17836.java
  yeonjae/src/week18/BOJ_17836_공주님을구해라/README.md
Labels: 🏃‍♂️DFS/BFS

#415 최연재 : BOJ 17218 비밀번호 만들기
  yeonjae/src/week18/BOJ_17218_비밀번호만들기/BOJ17218.java
  yeonjae/src/week18/BOJ_17218_비밀번호만들기/README.md
Labels: 🏁DP

#430 최연재 : BOJ 2666 벽장문의 이동
  yeonjae/src/week18/BOJ_2666_벽장문의_이동/BOJ2666.java
  yeonjae/src/week18/BOJ_2666_벽장문의_이동/README.md
Labels: 👊브루트포스

#431 최연재 : BOJ 16197 두 동전
  yeonjae/src/week18/BOJ_16197_두_동전/BOJ16197.java
  yeonjae/src/week18/BOJ_16197_두_동전/README.md
Labels: 🏃‍♂️DFS/BFS

#433 최연재 : BOJ 1937 욕심쟁이 판다
  yeonjae/src/week18/BOJ_1937_욕심쟁이_판다/BOJ1937.java
  yeonjae/src/week18/BOJ_1937_욕심쟁이_판다/README.md
Labels: 🏁DP

#439 강다은 : BOJ 17218 G5 비밀번호 만들기
  daeun/src/weej=k18/BOJ_17218_G5_비밀번호만들기/Main.java
  daeun/src/weej=k18/BOJ_17218_G5_비밀번호만들기/README.md
Labels: 🏁DP

#417 강다은 : BOJ 1937 G3 욕심쟁이 판다
  daeun/src/week18/BOJ_1937_G3_욕심쟁이판다/Main.java
  daeun/src/week18/BOJ_1937_G3_욕심쟁이판다/README.md
Labels: 🏁DP, 🏃‍♂️DFS/BFS

#421 강다은 : BOJ 16197 G4 두 동전
  daeun/src/week18/BOJ_16197_G4_두동전/Main.java
  daeun/src/week18/BOJ_16197_G4_두동전/README.md
Labels: 🏃‍♂️DFS/BFS

#429 강다은 : BOJ 17836 G5 공주님을 구해라!
  daeun/src/week18/BOJ_17836_G5_공주님을구해라/Main.java
  daeun/src/week18/BOJ_17836_G5_공주님을구해라/README.md
Labels: 🏃‍♂️DFS/BFS

#432 강다은 : BOJ 2666 G5 벽장문의 이동
  daeun/src/week18/BOJ_2666_G5_벽장문의이동/Main.java
  daeun/src/week18/BOJ_2666_G5_벽장문의이동/README.md
Labels: 🏃‍♂️DFS/BFS

#444 최영은 : BOJ 1937 G3 욕심쟁이판다
  yeongeun/src/week18/BOJ_1937_G3_욕심쟁이판다/Main.java
  yeongeun/src/week18/BOJ_1937_G3_욕심쟁이판다/README.md
Labels: 🏁DP, 🏃‍♂️DFS/BFS

#443 최영은 : BOJ 2666 G5 벽장문의이동
  yeongeun/src/week18/BOJ_2666_벽장문의이동/Main2666_벽장문의이동.java
  yeongeun/src/week18/BOJ_2666_벽장문의이동/README.md
Labels: 🏁DP, 👨🏻‍🤝‍👨🏻그래프

#442 최영은 : BOJ 17836 G5 공주님을 구해라
  yeongeun/src/week18/BOJ_17836_G5_공주님을구해라/Main17836_공주님을구해라.java
  yeongeun/src/week18/BOJ_17836_G5_공주님을구해라/README.md
Labels: 🏃‍♂️DFS/BFS

#441 최영은 : BOJ 16197 G4 두동전
  yeongeun/src/week18/BOJ_16197_G4_두동전/Main16197_두동전.java
  yeongeun/src/week18/BOJ_16197_G4_두동전/README.md
Labels: 🏃‍♂️DFS/BFS

#440 최영은 : BOJ 17218 G5 비밀번호만들기
  yeongeun/src/week18/BOJ_17218_비밀번호만들기/Main17218_비밀번호만들기.java
  yeongeun/src/week18/BOJ_17218_비밀번호만들기/README.md
Labels: 🏁DP

#416 정효인 : BOJ 17836 공주님을 구해라!
  hyoin/src/week18/BOJ_17836_G5_공주님을구해라/BOJ_17836_G5_공주님을구해라.java
  hyoin/src/week18/BOJ_17836_G5_공주님을구해라/README.md
  hyoin/src/week18/README.md
Labels: 🏃‍♂️DFS/BFS

#428 강소현 : BOJ 17836 G5 공주님을 구해라
  sohyeon/src/week18/BOJ_17836_G5_공주님을구해라/Main.java
  sohyeon/src/week18/BOJ_17836_G5_공주님을구해라/README.md
Labels: 🏃‍♂️DFS/BFS

#424 강소현 : BOJ 1937 G3 욕심쟁이판다
  sohyeon/src/week18/BOJ_1937_G3_욕심쟁이판다/Main.java
  sohyeon/src/week18/BOJ_1937_G3_욕심쟁이판다/README.md
Labels: 🏁DP, 🏃‍♂️DFS/BFS

#425 강소현 : BOJ 1666 G5 벽장문의이동
  sohyeon/src/week18/BOJ_2666_G5_벽장문의이동/Main.java
  sohyeon/src/week18/BOJ_2666_G5_벽장문의이동/README.md
Labels: 🏃‍♂️DFS/BFS

#427 강소현 : BOJ 17218 G5 비밀번호만들기
  sohyeon/src/week18/BOJ_17218_G5_비밀번호만들기/Main.java
  sohyeon/src/week18/BOJ_17218_G5_비밀번호만들기/README.md
Labels: 🏁DP

#426 강소현 : BOJ 16197 G4 두 동전
  sohyeon/src/week18/BOJ_16197_G4_두동전/Main.java
  sohyeon/src/week18/BOJ_16197_G4_두동전/README.md
Labels: 🏃‍♂️DFS/BFS

#459 강다은 : BOJ 22945 G4 팀 빌딩
  daeun/src/week19/BOJ_22945_G4_팀빌딩/Main.java
  daeun/src/week19/BOJ_22945_G4_팀빌딩/README.md
Labels: 🔫투포인터

#454 강다은 : BOJ 8983 G4 사냥꾼
  daeun/src/week19/BOJ_8983_G4_사냥꾼/Main.java
  daeun/src/week19/BOJ_8983_G4_사냥꾼/README.md
Labels: 🧦이분탐색

#446 최연재 : BOJ 2615 S1 오목
  yeonjae/src/week19/BOJ_2615_오목/BOJ2615.java
  yeonjae/src/week19/BOJ_2615_오목/README.md
Labels: 🤜구현

#447 최연재 : BOJ 14938 G4 서강그라운드
  yeonjae/src/week19/BOJ_14938_서강그라운드/BOJ14938.java
  yeonjae/src/week19/BOJ_14938_서강그라운드/README.md
Labels: 👨🏻‍🤝‍👨🏻그래프

#448 최연재 : BOJ 8983 G4 사냥꾼
  yeonjae/src/week19/BOJ_8983_사냥꾼/BOJ8983.java
  yeonjae/src/week19/BOJ_8983_사냥꾼/README.md
Labels: 🧦이분탐색

#449 최연재 : BOJ 22945 G4 팀 빌딩
  yeonjae/src/week19/BOJ_22945_팀빌딩/BOJ22945.java
  yeonjae/src/week19/BOJ_22945_팀빌딩/README.md
Labels: 🔫투포인터

#452 이하린 : BOJ 2615 S1 오목
  harin/week19/BOJ_2615_S1_오목/BOJ_2615_S1_오목.java
  harin/week19/BOJ_2615_S1_오목/README.md
  harin/week19/README.md
Labels: 🤜구현

#450 강다은 : BOJ 2615 S1 오목
  daeun/src/week19/BOJ_2615_S1_오목/Main.java
  daeun/src/week19/BOJ_2615_S1_오목/README.md
Labels: 🤜구현

#451 강다은 : BOJ 14938 G4 서강 그라운드
  daeun/src/week19/BOJ_14938_G4_서강그라운드/Main.java
  daeun/src/week19/BOJ_14938_G4_서강그라운드/README.md
Labels: 👨🏻‍🤝‍👨🏻그래프
