Repository SSAFY9thBusan4-Algo/Algo-Study, pull requests merged in 2023-07, with the labels that each got.

#461 강소현 : BOJ 8983 G4 사냥꾼
  sohyeon/src/week19/BOJ_8983_G4_사냥꾼/Main.java
  sohyeon/src/week19/BOJ_8983_G4_사냥꾼/README.md
Labels: 🧦이분탐색

#462 강소현 : BOJ 2615 S1 오목
  sohyeon/src/week19/BOJ_2615_S1_오목/Main.java
  sohyeon/src/week19/BOJ_2615_S1_오목/README.md
Labels: 🔄 재귀

#463 강소현 : BOJ 14938 G4 서강그라운드
  sohyeon/src/week19/BOJ_14938_G4_서강그라운드/Main.java
  sohyeon/src/week19/BOJ_14938_G4_서강그라운드/README.md
Labels: 👨🏻‍🤝‍👨🏻그래프

#464 강소현 : BOJ 22945 G4 팀빌딩
  sohyeon/src/week19/BOJ_22945_G4_팀빌딩/Main.java
  sohyeon/src/week19/BOJ_22945_G4_팀빌딩/README.md
Labels: 🔫투포인터

#455 정효인 : BOJ 22945 G4 팀 빌딩
  hyoin/src/week19/BOJ_22945_G4_팀빌딩/BOJ_22945_G4_팀빌딩.java
  hyoin/src/week19/BOJ_22945_G4_팀빌딩/README.md
  hyoin/src/week19/README.md
Labels: 🔫투포인터

#473 김지홍 : BOJ_8983_G4_사냥꾼
  kjh95044/src/week19/BOJ_8983_G4_사냥꾼/BOJ_8983_G4_사냥꾼.java
  kjh95044/src/week19/BOJ_8983_G4_사냥꾼/readme.md
Labels: 🧦이분탐색

#472 김지홍 : BOJ_22945_G4_팀빌딩
  kjh95044/src/week19/BOJ_22945_G4_팀빌딩/BOJ_22945_G4_팀빌딩.java
  kjh95044/src/week19/BOJ_22945_G4_팀빌딩/readme.md
Labels: 🔫투포인터

#457 김지홍 : BOJ_2615_S1_오목
  kjh95044/src/week19/BOJ_2615_S1_오목/BOJ_2615_S1_오목.java
  kjh95044/src/week19/BOJ_2615_S1_오목/readme.md
Labels: 🤜구현

#466 김지홍 : BOJ_14938_G4_서강그라운드
  kjh95044/src/week19/BOJ_14938_G4_서강그라운드/BOJ_14938_G4_서강그라운드.java
  kjh95044/src/week19/BOJ_14938_G4_서강그라운드/readme.md
Labels: 플로이드 워샬

#468 최영은 : BOJ 14938 G4 서강그라운드
  yeongeun/src/week19/BOJ_14938_G4_서강그라운드/Main.java
  yeongeun/src/week19/BOJ_14938_G4_서강그라운드/README.md
Labels: 플로이드 워샬

#469 최영은 : BOJ 22945 G4 팀빌딩
  yeongeun/src/week19/BOJ_22945_G4_팀빌딩/Main.java
  yeongeun/src/week19/BOJ_22945_G4_팀빌딩/README.md
Labels: 🔫투포인터

#470 최영은 : BOJ 8983 G4 사냥꾼
  yeongeun/src/week19/BOJ_8983_G4_사냥꾼/Main.java
  yeongeun/src/week19/BOJ_8983_G4_사냥꾼/README.md
Labels: 🧦이분탐색

#471 최영은 : BOJ 2615 S1 오목
  yeongeun/src/week19/BOJ_2615_S1_오목/Main.java
  yeongeun/src/week19/BOJ_2615_S1_오목/README.md
Labels: 🤜구현

#482 강다은 : BOJ 1238 G3 파티
  daeun/src/week20/BOJ_1238_G3_파티/Main.java
  daeun/src/week20/BOJ_1238_G3_파티/README.md
Labels: 📌다익스트라

#481 강다은 : BOJ 12904 G5 A와 B
  daeun/src/week20/BOJ_12904_G5_A와B/Main.java
  daeun/src/week20/BOJ_12904_G5_A와B/README.md
Labels: 💬 문자열

#480 강다은 : BOJ 1188 G4 음식 평론가
  daeun/src/week20/BOJ_G4_1188_음식평론가/Main.java
  daeun/src/week20/BOJ_G4_1188_음식평론가/README.md
Labels: 수학

#487 정효인 : BOJ 1749 G4 점수따먹기
  hyoin/src/week20/BOJ_1749_G4_점수따먹기/BOJ_1749_G4_점수따먹기.java
  hyoin/src/week20/BOJ_1749_G4_점수따먹기/README.md
  hyoin/src/week20/README.md
Labels: 🏁DP, 🫴누적합

#474 이하린 : BOJ 12904 G5 A와 B
  harin/week20/BOJ_12904_G5_A와B/BOJ_12904_G5_A와B.java
  harin/week20/BOJ_12904_G5_A와B/README.md
  harin/week20/README.md
Labels: 💬 문자열

#476 최연재 : BOJ 1188 G4 음식평론가
  yeonjae/src/week20/BOJ_1188_음식평론가/BOJ1188.java
  yeonjae/src/week20/BOJ_1188_음식평론가/README.md
Labels: 수학

#477 최연재 : BOJ 1238 G3 파티
  yeonjae/src/week20/BOJ_1238_파티/BOJ1238.java
  yeonjae/src/week20/BOJ_1238_파티/README.md
Labels: 📌다익스트라

#478 최연재 : BOJ 1749 G4 점수따먹기
  yeonjae/src/week20/BOJ_1749_점수따먹기/BOJ1749.java
  yeonjae/src/week20/BOJ_1749_점수따먹기/README.md
Labels: 🫴누적합

#479 최연재 : BOJ 12904 G5 A와B
  yeonjae/src/week20/BOJ_12904_A와B/BOJ12904.java
  yeonjae/src/week20/BOJ_12904_A와B/README.md
Labels: 🤜구현

#490 최영은: BOJ 1749 G4 점수따먹기
  yeongeun/src/week20/BOJ_G4_점수따먹기/Main1749.java
  yeongeun/src/week20/BOJ_G4_점수따먹기/README.md
Labels: 🫴누적합

#491 최영은 : BOJ 12904 G5 A와B
  yeongeun/src/week20/BOJ_12904_G5_A와B/Main12904.java
  yeongeun/src/week20/BOJ_12904_G5_A와B/README.md
Labels: 💬 문자열

#492 최영은 : BOJ 1238 G3 파티
  yeongeun/src/week20/BOJ_1238_G3_파티/Main1238.java
  yeongeun/src/week20/BOJ_1238_G3_파티/README.md
Labels: 📌다익스트라

#493 최영은 : BOJ 1188 G4 음식평론가
  yeongeun/src/week20/BOJ_1188_G4_음식평론가/Main1188.java
  yeongeun/src/week20/BOJ_1188_G4_음식평론가/README.md
Labels: 수학

#495 강다은 : BOJ 1726 G3 로봇
  daeun/src/week21/BOJ_1726_G3_로봇/Main.java
  daeun/src/week21/BOJ_1726_G3_로봇/README.md
Labels: 🏃‍♂️DFS/BFS

#496 강다은 : BOJ 2448 G4 별 찍기 - 11
  daeun/src/week21/BOJ_2448_G4_별찍기-11/Main.java
  daeun/src/week21/BOJ_2448_G4_별찍기-11/README.md
Labels: 🤜구현

#494 이하린 : BOJ 1744 G4 수 묶기
  harin/week21/BOJ_1744_G4_수묶기/BOJ_1744_G4_수묶기.java
  harin/week21/BOJ_1744_G4_수묶기/README.md
  harin/week21/README.md
Labels: 💰 그리디

#502 강다은 : BOJ 2623 G3 음악프로그램
  daeun/src/week21/BOJ_2623_G3_음악프로그램/Main.java
  daeun/src/week21/BOJ_2623_G3_음악프로그램/README.md
Labels: ➡위상정렬

#501 강다은 : BOJ 1744 G4 수 묶기
  daeun/src/week21/BOJ_1744_G4_수묶기/Main.java
  daeun/src/week21/BOJ_1744_G4_수묶기/README.md
Labels: 💰 그리디

#505 최연재 : BOJ 1726 G3 로봇
  yeonjae/src/week21/BOJ_1726_로봇/BOJ1726.java
  yeonjae/src/week21/BOJ_1726_로봇/README.md
Labels: 🏃‍♂️DFS/BFS

#506 최연재 : BOJ 2448 G4 별찍기11
  yeonjae/src/week21/BOJ_2448_별찍기11/BOJ2448.java
  yeonjae/src/week21/BOJ_2448_별찍기11/README.md
Labels: 🏃‍♂️DFS/BFS

#507 최연재 : BOJ 1744 G4 수 묶기
  yeonjae/src/week21/BOJ_1744_수_묶기/BOJ1744.java
  yeonjae/src/week21/BOJ_1744_수_묶기/README.md
Labels: 🤜구현

#508 최연재 : BOJ 2623 G3 음악프로그램
  yeonjae/src/week21/BOJ_2623_음악프로그램/BOJ2623.java
  yeonjae/src/week21/BOJ_2623_음악프로그램/README.md
Labels: 👨🏻‍🤝‍👨🏻그래프

#497 정효인 : BOJ 1726 G3 로봇
  hyoin/.idea/.gitignore
  hyoin/.idea/misc.xml
  hyoin/.idea/vcs.xml
  hyoin/src/week21/BOJ_1726_G3_로봇/BOJ_1726_G3_로봇.java
  hyoin/src/week21/BOJ_1726_G3_로봇/README.md
  hyoin/src/week21/README.md
Labels: 🏃‍♂️DFS/BFS

#509 최영은 : BOJ 1726 G3 로봇
  yeongeun/src/week21/BOJ_1726_G3_로봇/Main.java
  yeongeun/src/week21/BOJ_1726_G3_로봇/README.md
Labels: 🏃‍♂️DFS/BFS

#510 최영은 : BOJ 2448 G4 별찍기-11
  yeongeun/src/week21/BOJ_2448_G4_별찍기-11/Main.java
  yeongeun/src/week21/BOJ_2448_G4_별찍기-11/README.md
Labels: 🔄 재귀

#512 최영은 : BOJ_1744_G4_수묶기
  yeongeun/src/week21/BOJ_1744_G4_수묶기/Main.java
  yeongeun/src/week21/BOJ_1744_G4_수묶기/README.md
Labels: 💰 그리디

#515 최영은 : BOJ 2623 G3 음악프로그램
  yeongeun/src/week21/BOJ_2623_G3_음악프로그램/Main.java
  yeongeun/src/week21/BOJ_2623_G3_음악프로그램/README.md
Labels: ➡위상정렬

#518 강소현 : BOJ 1726 G3 로봇
  sohyeon/src/week21/BOJ_1726_G3_로봇/Main.java
  sohyeon/src/week21/BOJ_1726_G3_로봇/README.md
Labels: 🏃‍♂️DFS/BFS

#514 김지홍 : BOJ 2448 G4 별찍기11
  kjh95044/src/week21/BOJ_2448_G4_별찍기11/BOJ_2448_G4_별찍기11.java
  kjh95044/src/week21/BOJ_2448_G4_별찍기11/readme.md
Labels: 🔄 재귀

#516 김지홍 : BOJ 1744 G4 수 묶기
  kjh95044/src/week21/BOJ_1744_G4_수묶기/BOJ_1744_G4_수묶기.java
  kjh95044/src/week21/BOJ_1744_G4_수묶기/readme.md
Labels: 💰 그리디

#517 김지홍 : BOJ 2623 G3 음악프로그램
  kjh95044/src/week21/BOJ_2623_G3_음악프로그램/BOJ_2623_G3_음악프로그램.java
  kjh95044/src/week21/BOJ_2623_G3_음악프로그램/readme.md
Labels: ➡위상정렬

#536 정효인 : BOJ 15684 G3 사다리조작
  hyoin/src/week22/BOJ_15684_G3_사다리조작/BOJ_15684_G3_사다리조작.java
  hyoin/src/week22/BOJ_15684_G3_사다리조작/README.md
Labels: 🏃‍♂️DFS/BFS

#539 정효인 : BOJ 2831 G4 댄스파티
  hyoin/src/week22/BOJ_2831_G4_댄스파티/BOJ_2831_G4_댄스파티.java
  hyoin/src/week22/BOJ_2831_G4_댄스파티/README.md
Labels: 💰 그리디

#538 정효인 : BOJ 2056 G4 작업
  hyoin/src/week22/BOJ_2056_G4_작업/BOJ_2056_G4_작업.java
  hyoin/src/week22/BOJ_2056_G4_작업/README.md
Labels: 🏁DP, ➡위상정렬

#537 정효인 : BOJ 14226 G4 이모티콘
  hyoin/src/week22/BOJ_14226_G4_이모티콘/BOJ_14226_G4_이모티콘.java
  hyoin/src/week22/BOJ_14226_G4_이모티콘/README.md
Labels: 🏃‍♂️DFS/BFS

#532 강다은 : BOJ 2056 G4 작업
  daeun/src/week22/BOJ_2056_G4_작업/Main.java
  daeun/src/week22/BOJ_2056_G4_작업/README.md
Labels: ➡위상정렬

#531 강다은 : BOJ 2831 G4 댄스 파티
  daeun/src/week22/BOJ_2831_G4_댄스파티/Main.java
  daeun/src/week22/BOJ_2831_G4_댄스파티/README.md
Labels: 🔫투포인터

#523 강다은 : BOJ 15684 G3 사다리 조작
  daeun/src/week22/BOJ_15684_G3_사다리조작/Main.java
Labels: 🏃‍♂️DFS/BFS, 🤜구현

#530 최연재 : BOJ 14226 G4 이모티콘
  yeonjae/src/week22/BOJ_14226_이모티콘/BOJ14226.java
  yeonjae/src/week22/BOJ_14226_이모티콘/README.md
Labels: 🏃‍♂️DFS/BFS

#529 최연재 : BOJ 15684 G3 사다리조작
  yeonjae/src/week22/BOJ_15684_사다리조작/BOJ15684.java
  yeonjae/src/week22/BOJ_15684_사다리조작/README.md
Labels: 🏃‍♂️DFS/BFS, 🤜구현

#528 최연재 : BOJ 2831 G4 댄스파티
  yeonjae/src/week22/BOJ_2831_댄스파티/BOJ2831.java
  yeonjae/src/week22/BOJ_2831_댄스파티/README.md
Labels: ⬇️큐

#527 최연재 : BOJ 2056 G4 작업
  yeonjae/src/week22/BOJ_2056_작업/BOJ2056.java
  yeonjae/src/week22/BOJ_2056_작업/README.md
Labels: ➡위상정렬

#526 이동주 : BOJ 2831 G4 댄스파티
  dongju/src/week22/이동주-BOJ-2831-G4-댄스파티/README.md
  dongju/src/week22/이동주-BOJ-2831-G4-댄스파티/이동주-BOJ-2831-G4-댄스파티.js
Labels: 💰 그리디, 🔫투포인터

#552 정효인 : BOJ 15565 S1 귀여운라이언
  hyoin/src/week23/BOJ_15565_S1_귀여운라이언/BOJ_15565_S1_귀여운라이언.java
  hyoin/src/week23/BOJ_15565_S1_귀여운라이언/README.md
Labels: 🔫투포인터

#551 정효인 : BOJ 13335 S1 트럭
  hyoin/src/week23/BOJ_13335_S1_트럭/BOJ_13335_S1_트럭.java
  hyoin/src/week23/BOJ_13335_S1_트럭/README.md
Labels: ⬇️큐

#540 강다은 : BOJ 1939 G3 중량제한
  daeun/src/week23/BOJ_1939_G3_중량제한/Main.java
  daeun/src/week23/BOJ_1939_G3_중량제한/README.md
Labels: 🏃‍♂️DFS/BFS, 🧦이분탐색

#541 강다은 : BOJ 13335 S1 트럭
  daeun/src/week23/BOJ_13335_S1_트럭/Main.java
  daeun/src/week23/BOJ_13335_S1_트럭/README.md
Labels: ⬇️큐

#550 강다은 : BOJ 7453 G2 합이 0인 네 정수
  daeun/src/week23/BOJ_7453_G2_합이0인네정수/Main.java
  daeun/src/week23/BOJ_7453_G2_합이0인네정수/README.md
Labels: 🔫투포인터

#546 강다은 : BOJ 15565 S1 귀여운 라이언
  daeun/src/week23/BOJ_15565_귀여운라이언/Main.java
  daeun/src/week23/BOJ_15565_귀여운라이언/README.md
Labels: 🔫투포인터

#542 강소현 : BOJ 1939 G3 중량제한
  sohyeon/src/week23/BOJ_1939_G3_중량제한/Main.java
  sohyeon/src/week23/BOJ_1939_G3_중량제한/README.md
Labels: 🏃‍♂️DFS/BFS

#543 강소현 : BOJ 7453 G2 합이0인네정수
  sohyeon/src/week23/BOJ_7453_G2_합이0인네정수/Main.java
  sohyeon/src/week23/BOJ_7453_G2_합이0인네정수/README.md
Labels: 🔫투포인터

#544 강소현 : BOJ 13335 S2 트럭
  sohyeon/src/week23/BOJ_13335_S1_트럭/Main.java
  sohyeon/src/week23/BOJ_13335_S1_트럭/README.md
Labels: ⬇️큐

#545 강소현 : BOJ 15565 S1 귀여운라이언
  sohyeon/src/week23/BOJ_15565_S1_귀여운라이언/Main.java
  sohyeon/src/week23/BOJ_15565_S1_귀여운라이언/README.md
Labels: 🔫투포인터

#547 최연재 : BOJ 13335 S1 트럭
  yeonjae/src/week23/BOJ_13335_트럭/BOJ13335.java
  yeonjae/src/week23/BOJ_13335_트럭/README.md
Labels: ⬇️큐

#548 최연재 : BOJ 15565 S1 귀여운라이언
  yeonjae/src/week23/BOJ_15565_귀여운라이언/BOJ15565.java
  yeonjae/src/week23/BOJ_15565_귀여운라이언/README.md
Labels: 🤜구현

#549 최연재 : BOJ 1939 G3 중량제한
  yeonjae/src/week23/BOJ_1939_중량제한/BOJ1939.java
  yeonjae/src/week23/BOJ_1939_중량제한/README.md
Labels: 👨🏻‍🤝‍👨🏻그래프

#553 최연재 : BOJ 7453 G2 합이 0인 네 정수
  yeonjae/src/week23/BOJ_7453_합이0인_네정수/BOJ7453.java
  yeonjae/src/week23/BOJ_7453_합이0인_네정수/README.md
Labels: 🤜구현, 🧦이분탐색
